"""Central ordered sidebar navigation (replaces Streamlit's autogenerated page list)."""

from __future__ import annotations

import streamlit as st

from app.state import PAGE_KEY, PENDING_PAGE_KEY

PAGES = [
    "Executive Overview",
    "Claim Diagnostic",
    "Creator Strategy",
    "Multimodal RAG",
    "Governance & Roadmap",
    "Methodology & Limitations",
]


_NAV_WIDGET_KEY = "_cockpit_nav_radio_widget"


def render_sidebar_nav() -> str:
    st.sidebar.markdown("### TALA Decision Cockpit")

    # Apply any pending programmatic navigation (go_to_page/send_claim_to_rag)
    # to the radio's own widget key *before* instantiating it this run, then
    # clear the request. Ordinary user clicks never touch PENDING_PAGE_KEY, so
    # they always flow straight through Streamlit's normal widget mechanism
    # below -- this indirection exists only so a page-render function can
    # request navigation without touching the widget's key after it has
    # already been instantiated this run (which Streamlit forbids), and it
    # never depends on whether the previously rendered page raised an error.
    pending = st.session_state.pop(PENDING_PAGE_KEY, None)
    if pending in PAGES:
        st.session_state[_NAV_WIDGET_KEY] = pending
    elif st.session_state.get(_NAV_WIDGET_KEY) not in PAGES:
        st.session_state[_NAV_WIDGET_KEY] = PAGES[0]

    selected = st.sidebar.radio("Navigate", PAGES, key=_NAV_WIDGET_KEY, label_visibility="collapsed")
    st.session_state[PAGE_KEY] = selected
    st.sidebar.divider()
    return selected
