"""TALA Multimodal AI Decision Cockpit -- executive multi-page Streamlit entry point.

Launch: streamlit run app\\streamlit_app.py

Six pages (central sidebar navigation, not autogenerated Streamlit pages):
Executive Overview, Claim Diagnostic, Creator Strategy, Multimodal RAG,
Governance & Roadmap, Methodology & Limitations.

Analytics pages (everything except Multimodal RAG) load only cached,
pre-validated CSVs from outputs/tables/ via app.data_loader and never import
RAG/embedding/Gemini modules -- those are imported lazily inside
app.views.rag_explorer.render(), and Gemini is only called after the user
explicitly submits a query there.
"""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app import data_loader as dl
from app.components.navigation import render_sidebar_nav
from app.state import init_state
from app.styling import inject_css
from app.views import claim_diagnostic, creator_strategy, executive_overview, governance, methodology, rag_explorer

st.set_page_config(page_title="TALA Multimodal AI Decision Cockpit", layout="wide")
inject_css()
init_state()

page = render_sidebar_nav()

RENDERERS = {
    "Executive Overview": executive_overview.render,
    "Claim Diagnostic": claim_diagnostic.render,
    "Creator Strategy": creator_strategy.render,
    "Multimodal RAG": rag_explorer.render,
    "Governance & Roadmap": governance.render,
    "Methodology & Limitations": methodology.render,
}

try:
    RENDERERS[page]()
except dl.MissingTableError as exc:
    st.error(f"This page could not load a required analytical output: {exc}")
except Exception as exc:  # noqa: BLE001 -- executive-facing pages must never show a raw traceback
    st.error(
        "This page hit an unexpected error and could not render. "
        "Technical detail has been withheld from this view; check the terminal log for full details."
    )
    print(f"[cockpit] unhandled error on page '{page}': {exc!r}", file=sys.stderr)
    st.stop()
